### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by LifeHacker125132** [JojocraftTv/Discord-Token-Grabber-Java#1]
error: incompatible types: String cannot be converted to Map
                    return new JSONObject(line).getJSONObject("os_crypt").getString("encrypted_key");
![image](https://user-images.githubusercontent.com/49880812/184190068-294de705-114e-44ce-91bb-7372456e5af2.png)

**Comment by JojocraftTv** [comment]
Hey, Thanks for the Report.

Are you sure that you are using the correct org.json?
I used org.json 20220320
https://mvnrepository.com/artifact/org.json/json/20220320
For me it works fine. If you are using some other lib, rewrite this line, or change to org.json (20220320)

(I added mvnrepository links to Readme)

**Comment by LifeHacker125132** [comment]
thanks for help
